baseURL = 'https://pactus.org'
title = 'Pactus blockchain'
languageCode = 'en'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
relativeURLs = true

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"

[params]
  latestVersion = "1.3.0"
  mainCSS = "css/main.css"
  subtitle = 'Building decentralized future together!'
  [params.contact]
    email = 'info@pactus.org'

[languages]
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Pactus blockchain'
    weight = 1
    [languages.en.params]
      subtitle = 'Building decentralized future together!'

  [languages.ar]
    contentDir = 'content/ar'
    disabled = false
    languageCode = 'ar'
    languageDirection = 'rtl'
    languageName = 'العربية'
    title = 'بلوكشين بكتوس"'
    weight = 2
    [languages.ar.params]
      subtitle = 'نبني مستقبل لامركزي معا!'

  [languages.zh]
    contentDir = 'content/zh'
    disabled = false
    languageCode = 'zh'
    languageDirection = 'ltr'
    languageName = '中文'
    title = 'Pactus 区块链'
    weight = 3
    [languages.zh.params]
      subtitle = '共同构建去中心化的未来！'

[markup]
  [markup.goldmark]
    duplicateResourceFiles = false
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      [markup.goldmark.extensions.cjk]
        eastAsianLineBreaks = false
        eastAsianLineBreaksStyle = 'simple'
        enable = false
        escapedSpace = false
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = false
        [markup.goldmark.extensions.extras.insert]
          enable = false
        [markup.goldmark.extensions.extras.mark]
          enable = false
        [markup.goldmark.extensions.extras.subscript]
          enable = false
        [markup.goldmark.extensions.extras.superscript]
          enable = false
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
      [markup.goldmark.extensions.typographer]
        apostrophe = '&rsquo;'
        disable = false
        ellipsis = '&hellip;'
        emDash = '&mdash;'
        enDash = '&ndash;'
        leftAngleQuote = '&laquo;'
        leftDoubleQuote = '&ldquo;'
        leftSingleQuote = '&lsquo;'
        rightAngleQuote = '&raquo;'
        rightDoubleQuote = '&rdquo;'
        rightSingleQuote = '&rsquo;'
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = false
      [markup.goldmark.renderHooks.link]
        enableDefault = false
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false